### PR TITLE
Add ES6-style snippets

### PR DESCRIPTION
**Pull request by stremlenye**

### CODE REVIEW

**Comment by DjebbZ** [comment]
What would it take to make the build on AppVeyor pass ? The error seems to come from the fact that Chocolatey is prompting the user, of course it doesn't exist on CI. Should it be merged anyway, since the tests pass on Travis ?

**Comment by orktes** [comment]
Hi, Travis is enough! Thanks for contributing!

**Comment by DjebbZ** [comment]
Nice !
Do you know when you'll make a new release of the package ?

**Comment by stremlenye** [comment]
I think I'll add some more ES6 snippets today and also apply some fixes to existing ones.

**Comment by DjebbZ** [comment]
Ok, good to know. Thanks for your package btw, it works very well.

**Comment by orktes** [comment]
New version published and webpage updated to contain new snippets.

**Comment by stremlenye** [comment]
:+1:

**Comment by IngenieroLata** [comment]
I just updated to 0.12.1 and the ES6 snippets are not working. Is there some extra thing to do on the key binding or something?

**Comment by IngenieroLata** [comment]
Just edited the /

**Comment by IngenieroLata** [comment]
I made it work by editing snippets/Javascript(JSX).cson 

commentend in line 81 
```
  # React >0.13 (ES6)
  # ".source.js":
```
and reindented the lines for ES6 

also I changed the snippet for rcc6 for this 

```
    prefix: 'rcc6'
    body: 'import React from \'react\';\n\nclass $1 extends React.Component{\n\trender () {\n\t\treturn (\n\t\n\t\t);\n\t}\n}\n\nexport default ${1};\n'
```

**Comment by IngenieroLata** [comment]
I made it work by editing the file sippets/JavaScritp (JSX).cson

comment the line 80
```
79   # React >0.13 (ES6)
80   # ".source.js":
```
and change the name of all the ES6 snippets from React: ...  to  ReactES6: .... 

```
"ReactES6: componentDidMount() { ... }":
"ReactES6: componentDidUpdate(pp, ps) { ... }":
"ReactES6: componentWillMount() { ... }":
"ReactES6: componentWillReceiveProps(np) { ... }":
```

also I changed the rcc6 body to: 
```
    prefix: 'rcc6'
    body: 'import React from \'react\';\n\nclass $1 extends React.Component{\n\trender () {\n\t\treturn (\n\t\n\t\t);\n\t}\n}\n\nexport default ${1};\n'

```

**Pull request merged**
