### PR TITLE
Add required semicolon to static class properties

### LINKED ISSUE #135: Add semicolon to end of snippets `pt6` and `dp`
Class static properties require a trailing semicolon, and Babel is now throwing compilation errors if it doesn't find them (see https://phabricator.babeljs.io/T6873).  

The snippets currently generate:

```js
// dp - >
static defaultProps = {
    
}

// pt6 ->
static propTypes = {
    : React.PropTypes.string
}
```

Both of these will cause recent versions of Babel to crash.  I'm happy to submit a PR if you agree.

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #135

### CODE REVIEW

**Comment by IanVS** [comment]
Sorry for the trailing space changes (my Atom strips them out on save).  Should I take out those changes?

**Comment by jeffshaver** [comment]
This is going to get changed. Eventually babel will get reverted. @jeffmo is supposedly going to be talking to the babel team to get this figured out. I don't know that its worth doing if its just going to get reverted soon.

**Comment by IanVS** [comment]
As @orktes metioned in https://github.com/orktes/atom-react/issues/135#issuecomment-172005325, there's not really a harm to including them.

**Comment by jeffmo** [comment]
Assuming the style for this codebase is to use semicolons (rather than rely on ASI), might as well leave these in. Arguably for those who prefer to use explicit semicolons, there should probably be a lint error to cover these cases

**Comment by jeffshaver** [comment]
Maybe this should be an option? Honestly, I don't use snippets at all, so I don't particularly mind. But if I did, and there was a semi-colon there every time, i would probably just not use it.

**Comment by IanVS** [comment]
> Maybe this should be an option?

That's probably not a bad idea.  It seems that right now there's inconsistency in whether semicolons are generated or not.  I'd really love if this could get merged though as at least an intermediate step.

**Pull request merged**
