### PR TITLE
Fixes #36. Add condition to decreaseIndentPattern regex to support self closing-tags

### PR DESCRIPTION
**Pull request by jeffshaver**
If there is any more info you need, please let me know.

I assume that i will need to add some tests maybe, but I didn't see the correct place to put them. Guidance there?

### CODE REVIEW

**Comment by orktes** [comment]
Hi!

Thanks for contributing!

Indentation test file is located in
https://github.com/orktes/atom-react/blob/master/spec/fixtures/sample.jsx
and the expected result in
https://github.com/orktes/atom-react/blob/master/spec/fixtures/sample-formatted.jsx

So adding something like
```js
// sample.jsx
<div>
<span 
foo="bar"
bar="foo"
/>
<span barfoo="123" />
<span>
foo
</span>
</div>

// sample-formatted.jsx
<div>
  <span 
    foo="bar"
    bar="foo"
  />
  <span barfoo="123" />
  <span 
    foo="bar"
    bar="foo" />
  <span>
    foo
  </span>
</div>
```
ps. currently it seems that one tokenizer test is failing against the latest lang-javascript package that atom-react is extending with JSX. Feel free to ignore that for now.

**Comment by orktes** [comment]
ps ignore appveyor (I should remove that as it causes more trouble than it helps)

**Comment by jeffshaver** [comment]
@orktes thanks for the quick response!

Will work this later today (hopefully). Just to be clear in regards to #131, this isn't really reading the eslint config. I guess it may be possible to do that, but I didn't think it was necessary. This seems more like a bug than preference (to me, but I don't know if everyone writes jsx like me).

This is basically what I end up with when I use self-closing tags right now:

```
<MyComponent
  id="a"
  {...this.props}
  /> // Note how this is indented
```

All this pr does is this:
```
<MyComponent
  id="a"
  {...this.props}
/> // This line gets auto-unindented now
```

**Comment by orktes** [comment]
Yeap. My own preference has been to close after last attribute but
reasoning for putting it onto a separate line is clear.

I added a separate issue about the eslint conf stuff.

On Monday, 4 January 2016, Jeffrey E. Shaver II <notifications@github.com>
wrote:

> @orktes <https://github.com/orktes> thanks for the quick response!
>
> Will work this later today (hopefully). Just to be clear in regards to
> #131 <https://github.com/orktes/atom-react/pull/131>, this isn't really
> reading the eslint config. I guess it may be possible to do that, but I
> didn't think it was necessary. This seems more like a bug than preference
> (to me, but I don't know if everyone writes jsx like me).
>
> This is basically what I end up with when I use self-closing tags right
> now:
>
> <MyComponent
>   id="a"
>   {...this.props}
>   /> // Note how this is indented
>
> All this pr does is this:
>
> <MyComponent
>   id="a"
>   {...this.props}
> /> // This line gets auto-unindented now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/pull/131#issuecomment-168669048>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by jeffshaver** [comment]
@orktes I changed `sample.jsx` and `sample-formatted.jsx` and ran apm test. Only the one failed as you mentioned above.

**Comment by jeffshaver** [comment]
@orktes is there something else I need to do here?

**Comment by jeffshaver** [comment]
@orktes anything else on this?

**Comment by orktes** [comment]
Hi sorry for the delay. Been terribly busy with work. All good!

**Comment by orktes** [comment]
caused regression had to revert so we can release more urgent 1.4 related fixes.

**Pull request merged**
