### PR TITLE
stop treating js as jsx

### PR DESCRIPTION
**Pull request by bootsinpuss**

### CODE REVIEW

**Comment by bootsinpuss** [comment]
When this plugin makes js file as Javascript(JSX), a lot of other plugins for js stop working. Can we remove this ?

**Comment by orktes** [comment]
Hi,

Though this is a small change, it changes the functionality for thousands of users and I'm a little bit hesitant to do so as lots of people code JSX in JS files. Better option would be to find how to do this as a setting/programmatically rather than change the default functionality. In the meanwhile you can toggle normal javascript from the grammar menu.

Also can you list the plugins that stopped working?

**Comment by orktes** [comment]
Also next release of the package will extend language-javascript packages grammar so it should limit possible conflicts with other packages even more (as the tokens are exactly same).

**Comment by bootsinpuss** [comment]
Thanks for your response.

Current plugins conflict:

1. js file will be linted by jsxhint, which is a little different
2. snippets for js is not working
3. Symbols view is not working until my change is merged:
https://github.com/atom/symbols-view/blob/9143609e052361d932861c928ac16790c645932e/lib/tag-generator.coffee#L37-L38

I believe the next release will solve most of the problems if it extend language-javascript package.

**Comment by orktes** [comment]
Thanks for the list.

Snippets defined for js (source.js) should work just fine as the grammar scope name is defined as "source.js.jsx" (just confirmed this by my self).

I probably found a way to disable .js extension in code so I might be able to do a setting variable for the extensions list. With that people could actually even add more extensions if they need or remove ones they don't want (like in this case).

**Comment by orktes** [comment]
Hi! New version that extends language-javascript is now released.

**Comment by orktes** [comment]
Closing for now.

**Pull request closed without merging**
