### PR TITLE
Added .react.js extension

### PR DESCRIPTION
**Pull request by gyzerok**
Since its another popular extension for JSX files.

### CODE REVIEW

**Comment by orktes** [comment]
Hi! I haven't seen people using .react.js as the extension before. Any sources on how popular it is? Current require('react') detection should minimize the need for adding specific extensions for the grammar file.

**Comment by gyzerok** [comment]
@orktes Some people [using](https://scotch.io/tutorials/creating-a-simple-shopping-cart-with-react-js-and-flux) such name conevnsion. And i use it too. But since this package doesn't support it, i have to move to .jsx.
Also some people adds everywhere using modules into globals, to reduce boilerplate code with require for them (underscore/lodash, jquery, async, etc). So your detection with require doesn't work. Thats my case too and thats why i'm making this PR.

**Comment by gyzerok** [comment]
[One more example](https://github.com/jscs-dev/node-jscs/issues/374#issuecomment-43058803) of using .react.js i found just looking for es6 support in jscs :)

**Comment by orktes** [comment]
okay! :) I'll merge this but I might move adding/removing file extensions under package settings at some point to allow others to add custom extensions without having to add it directly to the grammar file.

**Comment by gyzerok** [comment]
@orktes Thnak you! I suppose adding functionality for customization trough settings would be great. Before this PR i've tried to found file extension customization settings in the package itself.

**Pull request merged**
