### PR TITLE
Add .jsxinc to file types

### PR DESCRIPTION
**Pull request by danielbayley**
Signed-off-by: Daniel Bayley <daniel.bayley@me.com>

### CODE REVIEW

**Comment by orktes** [comment]
Hi! This ads back the .js and .htc extensions removed in previous commit to master. Also can you describe what are .jsxinc files exactly? There should be no need to add extensions as the package already tries to find require('react') or es6 imports from the content to detect if the grammar should be selected.

**Comment by danielbayley** [comment]
I just cloned the repo and `.js` and `.htc` were included, I didn't write them back in.

**Comment by danielbayley** [comment]
I just cloned the repo to add the `.jsxinc` line. `.js` and `.htc` were included, I didn't write them back in.

`.jsxinc` is the convention for libraries to `#include` in [ExtendScript](http://en.wikipedia.org/wiki/ExtendScript) `.jsx` files, which this package targets. Have I got the wrong package?

**Comment by orktes** [comment]
This package targets Facebooks React.JS JSX syntax. So you most likely have the wrong package. Hope you find what you are looking for.

**Comment by orktes** [comment]
Also https://github.com/danielbayley/atom-react/commit/0922b2f4e10314b20e095c7edf06b8ff7b24a39e adds the .js and .htc extensions.

**Pull request closed without merging**
